apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-demo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ./charts/podinfo
    repoURL: https://github.com/<your-repo-name>/podinfo-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

